(() => {
  const STORE = 'ankaoFormalSimulatorV2';
  const USER_STORE = 'ankaoPlatformUserV1';
  const provinces = ['北京','天津','河北','山西','内蒙古','辽宁','大连','吉林','黑龙江','上海','江苏','浙江','安徽','福建','江西','山东','河南','湖北','湖南','广东','广西','海南','重庆','四川','贵州','云南','西藏','陕西','甘肃','青海','宁夏','新疆','兵团'];
  const titles = {dashboard:'账户信息',photo:'照片维护',personal:'个人基本信息维护',education:'学历学位信息维护',work:'工作经历维护',apply:'进入考试报名',review:'资格核查与缴费',form:'报名表预览',faq:'报考常见问题',guide:'新考生报名攻略'};
  const levelLabels = {all:'考全科',exempt1:'免一科',exempt2:'免二科',additional:'增报专业'};
  const educationLabels = {college:'大学专科',bachelor:'大学本科',second:'第二学士学位',master:'硕士学位',doctor:'博士学位'};
  const majorLabels = {related:'安全工程及相关专业',other:'其他专业'};
  const subjectLabels = {law:'安全生产法律法规',management:'安全生产管理',technology:'安全生产技术基础',practice:'安全生产专业实务'};
  const rules = {college:{related:5,other:6},bachelor:{related:3,other:4},second:{related:2,other:3},master:{related:1,other:2},doctor:{related:1,other:1}};
  const faqData = [
    ['account','首次报名必须先注册账号吗？','是。新考生通常需要先完成账号注册和身份、联系方式等信息维护。老考生一般无需重复注册，但应检查账号信息是否完整。'],
    ['account','忘记用户名或密码怎么办？','正式报名时应通过官方报名平台的账号找回功能处理；不要把账号密码提供给培训机构或他人。'],
    ['account','报名可以用手机操作吗？','部分操作可以在手机浏览器完成，但照片处理、材料上传和长表单填写更适合使用电脑。建议使用主流浏览器并保持网络稳定。'],
    ['account','注册信息填错了能修改吗？','未被系统锁定的信息通常可以自行维护。姓名、证件类型、证件号码等核心信息如有误，可能需要联系当地考试机构。'],
    ['photo','报名照片有什么要求？','通常要求近期彩色标准1寸、半身免冠正面证件照，白色背景，JPG或JPEG格式。正式要求以当年度报名系统提示为准。'],
    ['photo','照片一定要用审核工具处理吗？','正式系统一般要求使用指定照片审核处理工具，审核通过并保存后再上传。上传成功后照片可能无法自行更换。'],
    ['photo','照片上传后显示模糊怎么办？','不要反复压缩图片。应从原始证件照重新使用官方审核工具处理，并核对尺寸、背景和文件格式。'],
    ['education','学历信息一直显示未核查怎么办？','在线核查可能需要一定时间，可在提交后隔一段时间重新登录查看。不要在短时间内重复添加相同学历。'],
    ['education','学历在线核查未通过，还能继续报名吗？','通常可以先继续填写报考信息，但后续可能需要按报考地要求上传学信网验证或认证报告并接受人工核查。'],
    ['education','学历证书编号在哪里查询？','可查看毕业证书或登录学信网查询学历信息。演示系统中无需填写真实编号。'],
    ['education','非全日制学历可以报考吗？','符合国家承认学历及相应工作年限要求的，一般可以报考。工作年限计算和材料要求应以报考地考务通知为准。'],
    ['education','没有学位证书会影响报名吗？','报考条件主要看对应学历、专业和安全生产业务年限。无学位信息时通常可不填写学位，但应如实维护学历。'],
    ['education','可以添加多条学历信息吗？','正式报名系统通常允许维护多条学历学位信息，报名时选择其中符合报考条件且核查状态合适的一条。'],
    ['condition','其他专业可以报考中级注安吗？','可以。其他专业通常对应更长的安全生产业务工作年限，应按现行报考条件核对。'],
    ['condition','大专学历需要多少年安全工作经验？','安全工程及相关专业通常要求从事安全生产业务满5年，其他专业通常要求满6年。'],
    ['condition','本科学历需要多少年安全工作经验？','安全工程及相关专业通常要求满3年，其他专业通常要求满4年。'],
    ['condition','取得初级注册安全工程师后怎么报中级？','取得初级注册安全工程师职业资格后，从事安全生产业务满3年，可按该路径申请参加中级考试。'],
    ['condition','工作年限和专业年限有什么区别？','工作年限是参加正式工作的累计时间；专业年限是从事安全生产业务的累计时间。报名时两项应分别如实填写。'],
    ['condition','实习期能计入工作年限吗？','一般不把在校实习期计入正式工作年限。具体计算截止日期和证明口径以报考地考试机构要求为准。'],
    ['condition','年限刚好在考试当年达到，可以报名吗？','多数地区会明确工作年限计算截止日期，常见口径为报考年度年底。必须查看报考地当年度考务通知。'],
    ['subject','七个专业类别应该怎么选？','优先结合当前工作行业、未来职业方向和个人专业基础选择。没有明确行业方向时，可进一步比较各专业内容后决定。'],
    ['subject','考全科可以只报两门吗？','报考级别仍选择考全科，年度内通常可以根据个人安排勾选部分科目。成绩按规定周期滚动管理。'],
    ['subject','老考生已经通过部分科目怎么选级别？','仍按符合条件的报考级别报名，在科目选择时勾选尚未通过或计划报考的科目，不要把“免科”和已通过科目混淆。'],
    ['subject','增报专业是什么意思？','已经取得中级注册安全工程师职业资格后，再报名参加其他专业类别考试，通常可免试公共科目。'],
    ['subject','免一科和免二科分别是什么条件？','免一科、免二科涉及工程教育专业认证、高级职称及安全生产业务年限等条件，需由考试机构核验相关材料。'],
    ['audit','告知承诺制是什么意思？','选择采用告知承诺制，代表报考人员对符合条件和填报信息真实性作出承诺。考试机构仍可进行抽查和监管。'],
    ['audit','不采用告知承诺制可以报名吗？','可以，但通常需要按要求接受人工核查并提交相应证明材料，办理流程可能更长。'],
    ['audit','资格核查一般需要多久？','不同地区、不同核查方式时间不同，在线核查或人工核查结果应以报名系统提示和当地通知为准。'],
    ['audit','审核通过是不是就算报名成功？','不是。审核通过后还需要在规定时间内完成网上缴费；缴费成功通常才视为报名完成。'],
    ['audit','缴费后还能修改报名信息吗？','缴费完成后多数关键信息会被锁定，通常无法自行修改，因此缴费前必须再次核对。'],
    ['audit','报名表需要打印吗？','部分地区考后资格审核或单位存档可能会用到报名表，建议正式报名完成后下载并保存一份。'],
    ['audit','模拟审核通过代表正式报名能通过吗？','不代表。模拟结果只基于用户填写的信息和通用规则，最终结论以当地考试组织机构审核为准。']
  ];
  const defaultState = {
    view:'dashboard',photoComplete:false,personalComplete:false,educationComplete:false,workComplete:false,
    photoName:'',applicationStep:1,applicationSubmitted:false,reviewStatus:'none',paid:false,
    personal:{name:'模拟考生',gender:'男',birth:'1990-01-01',nation:'汉族',nationality:'中国',politics:'群众',phone:'138****0000',email:'demo@example.com'},
    education:{overseas:'no',certificate:'',school:'',graduation:'',majorName:'',level:'',mode:'普通全日制',degree:'无'},
    work:{company:'',companyType:'',province:'',startWork:'',startSafety:'',title:'无',titleDate:'',workYears:'',safetyYears:''},
    application:{exam:'2026年度中级注册安全工程师职业资格考试',province:'',level:'all',profession:'其他安全',subjects:['law','management','technology','practice'],condition:'',majorType:'related',junior:'no',middle:'no',promise:false}
  };
  let state = loadState();
  let platformUser = loadUser();
  const root = document.querySelector('#viewRoot');

  function loadState(){try{return merge(defaultState,JSON.parse(localStorage.getItem(STORE)||'{}'));}catch{return structuredClone(defaultState);}}
  function loadUser(){try{return JSON.parse(localStorage.getItem(USER_STORE)||'null');}catch{return null;}}
  function merge(base,extra){const out=structuredClone(base);Object.keys(extra||{}).forEach(k=>{out[k]=typeof out[k]==='object'&&!Array.isArray(out[k])&&typeof extra[k]==='object'?{...out[k],...extra[k]}:extra[k];});return out;}
  function save(){localStorage.setItem(STORE,JSON.stringify(state));updateChrome();}
  function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function completion(){return [state.photoComplete,state.personalComplete,state.educationComplete,state.workComplete].filter(Boolean).length*25;}
  function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300);}
  function openModal(id){const el=document.querySelector('#'+id);el.classList.add('open');el.setAttribute('aria-hidden','false');}
  function closeModal(id){const el=document.querySelector('#'+id);el.classList.remove('open');el.setAttribute('aria-hidden','true');}
  function updateChrome(){
    const pct=completion();
    document.querySelector('#sidePercent').textContent=pct+'%';document.querySelector('#sideProgress').style.width=pct+'%';
    const name=state.personal.name||'模拟考生';document.querySelector('#sideName').textContent=name;document.querySelector('#headerUser').textContent=name;document.querySelector('#avatarText').textContent=name.slice(0,1);
    document.querySelector('#breadcrumbTitle').textContent=titles[state.view];document.querySelector('#mobileTitle').textContent=titles[state.view];
    document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));
  }
  function panel(title,body,note=''){return `<div class="panel-title"><h2>${title}</h2><span>${note}</span></div><div class="panel-body">${body}</div>`;}
  function offer(title,desc,type='conditions'){return `<div class="conversion-offer"><div><strong>${title}</strong><span>${desc}</span></div><button data-open-lead data-offer="${type}">一键免费领取</button></div>`;}
  function statusCard(done,icon,title,desc,view){return `<button class="status-card ${done?'done':'warn'}" data-go="${view}"><i>${done?'✓':icon}</i><div><strong>${title}</strong><span>${done?'已完善':desc}</span></div></button>`;}
  function dashboard(){
    const pct=completion();
    return panel('账户信息',`<div class="tip-box"><strong>温馨提示：</strong>首次报考人员应先完成账号信息维护，信息完整度达到100%后再进入模拟考试报名。</div><div class="dashboard-top"><div class="welcome-card"><h2>${esc(state.personal.name)}，欢迎使用模拟报名服务平台</h2><p>当前为2026年度中级注册安全工程师新考生模拟报名流程。页面信息不会提交至任何考试机构。</p></div><div class="account-progress"><div><span>账号信息完整度</span><strong>${pct}%</strong></div><div class="large-progress"><i style="width:${pct}%"></i></div><small>${pct===100?'账号信息已完善，可以进入考试报名。':'请继续完成标记为待完善的项目。'}</small></div></div><div class="status-grid">${statusCard(state.photoComplete,'照','报名照片','待维护','photo')}${statusCard(state.personalComplete,'人','个人信息','待完善','personal')}${statusCard(state.educationComplete,'学','学历信息','待完善','education')}${statusCard(state.workComplete,'工','工作经历','待完善','work')}</div><div class="exam-section"><div class="section-head"><h3>考试报名</h3><span class="badge ${state.applicationSubmitted?'success':'gray'}">${state.applicationSubmitted?'已提交':'尚未提交'}</span></div><div class="exam-row"><div><h3>2026年度中级注册安全工程师职业资格考试</h3><p>模拟考试日期：2026年10月24日—25日　报名时间以报考地正式通知为准</p></div><button class="primary-btn" data-go="apply">${state.applicationSubmitted?'查看报名信息':'进入模拟报名'}</button></div></div><div class="button-row"><button class="secondary-btn" data-demo-fill>一键填充演示资料</button><button class="primary-btn" data-go="apply">开始完整报名流程</button></div>`,'新考生模拟流程');
  }
  function photo(){
    const preview=state.photoComplete?`<div class="demo-photo"><span>${esc(state.personal.name.slice(0,1)||'模')}</span><small>模拟证件照</small></div>`:'<span>暂无报名照片</span>';
    return panel('照片维护',`<div class="tip-box warning"><strong>安全提示：</strong>本演示系统不会上传或保存真实证件照。建议使用“生成模拟照片”体验流程。</div><div class="photo-layout"><div><div class="photo-preview" id="photoPreview">${preview}</div><div class="button-row"><button class="primary-btn" data-demo-photo>生成模拟照片</button><label class="secondary-btn upload-button">本地预览图片<input id="photoFile" type="file" accept="image/jpeg,image/png"></label></div></div><div class="photo-instructions"><h3>正式报名照片要求参考</h3><ol><li>近期彩色标准1寸、半身免冠正面证件照。</li><li>尺寸约25mm×35mm，像素295px×413px，白色背景。</li><li>JPG或JPEG格式，正式报名应使用照片审核处理工具。</li><li>照片将用于准考证、考场座次表及证书，请慎重选用。</li></ol><div class="tip-box">在正式报名系统中，照片上传成功后一般不允许自行更换。本页面只做本地预览。</div></div></div>`,'账号信息维护');
  }
  function row(label,control,required=true){return `<div class="form-row"><div class="form-label">${required?'<em>*</em> ':''}${label}</div><div class="form-control">${control}</div></div>`;}
  function opt(value,label,current){return `<option value="${value}" ${current===value?'selected':''}>${label}</option>`;}
  function personal(){const p=state.personal;return panel('个人基本信息维护',`<div class="tip-box"><strong>填写说明：</strong>正式报名中姓名、证件类型、证件号码、性别和出生日期通常来源于注册信息。本演示使用脱敏证件号，不要求填写真实身份证。</div><form id="personalForm" class="form-table">${row('姓名',`<input name="name" value="${esc(p.name)}" required maxlength="20"><small>用于模拟报名表显示</small>`)}${row('证件类型','<input value="居民身份证（模拟）" readonly>')}${row('证件号码','<input value="110***********1234" readonly>')}${row('性别',`<select name="gender">${opt('男','男',p.gender)}${opt('女','女',p.gender)}</select>`)}${row('出生日期',`<input name="birth" type="date" value="${esc(p.birth)}">`)}${row('民族',`<select name="nation">${opt('汉族','汉族',p.nation)}${opt('少数民族','少数民族',p.nation)}</select>`)}${row('国籍/地区',`<input name="nationality" value="${esc(p.nationality)}">`)}${row('政治面貌',`<select name="politics">${opt('群众','群众',p.politics)}${opt('中共党员','中共党员',p.politics)}${opt('共青团员','共青团员',p.politics)}${opt('其他','其他',p.politics)}</select>`)}${row('联系电话',`<input name="phone" value="${esc(p.phone)}" placeholder="演示可填写脱敏号码"><small>请勿在演示系统填写验证码</small>`)}${row('电子邮箱',`<input name="email" value="${esc(p.email)}" type="email">`,false)}</form><div class="button-row"><button class="primary-btn" data-save-personal>保存信息</button></div>`,'账号信息维护');}
  function education(){const e=state.education;const saved=state.educationComplete?`<table class="data-table"><thead><tr><th>学历层次</th><th>毕业院校</th><th>所学专业</th><th>毕业时间</th><th>核查状态</th></tr></thead><tbody><tr><td>${educationLabels[e.level]||'—'}</td><td>${esc(e.school)}</td><td>${esc(e.majorName)}</td><td>${esc(e.graduation)}</td><td><span class="badge success">模拟核查通过</span></td></tr></tbody></table>`:'';return panel('学历学位信息维护',`<div class="tip-box"><strong>核查提示：</strong>正式系统会对境内高等教育学历学位信息进行在线核查。核查未通过时，可能需要上传学信网验证或认证报告。</div>${saved}<h3 class="subheading">${state.educationComplete?'修改学历信息':'添加学历信息'}</h3><form id="educationForm" class="form-table">${row('是否境外院校',`<select name="overseas">${opt('no','否',e.overseas)}${opt('yes','是',e.overseas)}</select>`)}${row('毕业证书编号',`<input name="certificate" value="${esc(e.certificate)}" placeholder="演示编号即可"><small>请勿填写真实敏感编号</small>`)}${row('毕业院校',`<input name="school" value="${esc(e.school)}" required placeholder="请输入毕业院校">`)}${row('毕业时间',`<input name="graduation" type="month" value="${esc(e.graduation)}" required>`)}${row('所学专业',`<input name="majorName" value="${esc(e.majorName)}" required placeholder="请输入毕业证上的专业名称">`)}${row('学历层次',`<select name="level" required><option value="">请选择</option>${Object.entries(educationLabels).map(([v,l])=>opt(v,l,e.level)).join('')}</select>`)}${row('培养方式',`<select name="mode">${opt('普通全日制','普通全日制',e.mode)}${opt('成人教育','成人教育',e.mode)}${opt('自学考试','自学考试',e.mode)}${opt('网络教育','网络教育',e.mode)}${opt('其他','其他',e.mode)}</select>`)}${row('学位层次',`<select name="degree">${opt('无','无',e.degree)}${opt('学士','学士',e.degree)}${opt('硕士','硕士',e.degree)}${opt('博士','博士',e.degree)}</select>`,false)}</form><div class="button-row"><button class="primary-btn" data-save-education>保存并模拟核查</button></div>`,'账号信息维护');}
  function work(){const w=state.work;return panel('工作经历维护',`<div class="tip-box"><strong>填写说明：</strong>工作年限与专业年限含义不同。专业年限是指从事安全生产业务的累计年限，应与所选报考条件保持一致。</div><form id="workForm" class="form-table">${row('工作单位',`<input name="company" value="${esc(w.company)}" required placeholder="请输入当前或最近工作单位">`)}${row('单位性质',`<select name="companyType" required><option value="">请选择</option>${['国有企业','民营企业','事业单位','机关单位','外资企业','其他'].map(x=>opt(x,x,w.companyType)).join('')}</select>`)}${row('单位所在地',`<select name="province" required><option value="">请选择</option>${provinces.map(x=>opt(x,x,w.province)).join('')}</select>`)}${row('首次参加工作年月',`<input name="startWork" type="month" value="${esc(w.startWork)}" required>`)}${row('首次从事安全生产业务年月',`<input name="startSafety" type="month" value="${esc(w.startSafety)}" required>`)}${row('专业技术职称',`<select name="title">${['无','初级','中级','高级','正高级'].map(x=>opt(x,x,w.title)).join('')}</select>`)}${row('职称取得日期',`<input name="titleDate" type="date" value="${esc(w.titleDate)}">`,false)}${row('工作年限',`<input name="workYears" type="number" min="0" max="60" value="${esc(w.workYears)}" required><small>任何正式工作的累计年限</small>`)}${row('专业工作年限',`<input name="safetyYears" type="number" min="0" max="60" value="${esc(w.safetyYears)}" required><small>从事安全生产业务的累计年限</small>`)}</form><div class="button-row"><button class="primary-btn" data-save-work>保存工作经历</button></div>`,'账号信息维护');}
  function applyTimeline(){return `<div class="timeline">${['选择考试与地区','填写报考信息','确认个人资料','选择办理方式'].map((x,i)=>`<div class="${state.applicationStep===i+1?'active':state.applicationStep>i+1?'done':''}">${i+1}. ${x}</div>`).join('')}</div>`;}
  function application(){
    if(completion()<100)return panel('进入考试报名',`<div class="locked-box"><i>锁</i><h2>账号信息尚未完善</h2><p>请先完成照片、个人信息、学历信息和工作经历，信息完整度达到100%后再进入报名。</p><div class="button-row"><button class="secondary-btn" data-demo-fill>一键填充演示资料</button><button class="primary-btn" data-go="dashboard">返回账户信息</button></div></div>`,'考试报名');
    if(state.applicationSubmitted)return panel('报名信息查看',`${applyTimeline()}<div class="tip-box"><strong>当前状态：</strong>报考信息已提交，修改报名信息请先在模拟核查页面撤回。</div>${applicationSummary()}<div class="button-row"><button class="primary-btn" data-go="review">查看资格核查与缴费</button></div>`,'考试报名');
    let body=applyTimeline();const a=state.application;
    if(state.applicationStep===1)body+=`<div class="substep active"><div class="tip-box warning"><strong>属地提醒：</strong>报考人员原则上应在工作地或居住地报名，部分城市可能设置单独报名入口。</div><form id="applyStepForm" class="form-table">${row('考试名称',`<input name="exam" value="${esc(a.exam)}" readonly>`)}${row('报名省市',`<select name="province" required><option value="">请选择报考地区</option>${provinces.map(x=>opt(x,x,a.province)).join('')}</select>`)}${row('报考年度','<input value="2026年度（模拟）" readonly>')}</form></div>`;
    if(state.applicationStep===2){const req=a.majorType&&state.education.level?rules[state.education.level]?.[a.majorType]:null;body+=`<div class="substep active"><form id="applyStepForm" class="form-table">${row('报考级别',`<select name="level">${Object.entries(levelLabels).map(([v,l])=>opt(v,l,a.level)).join('')}</select>`)}${row('报考专业',`<select name="profession">${['煤矿安全','金属非金属矿山安全','化工安全','金属冶炼安全','建筑施工安全','道路运输安全','其他安全'].map(x=>opt(x,x,a.profession)).join('')}</select>`)}${row('报考科目',`<div class="subject-options">${Object.entries(subjectLabels).map(([v,l])=>`<label><input type="checkbox" name="subjects" value="${v}" ${a.subjects.includes(v)?'checked':''}>${l}</label>`).join('')}</div>`)}${row('专业类别',`<select name="majorType"><option value="">请选择</option>${opt('related','安全工程及相关专业',a.majorType)}${opt('other','其他专业',a.majorType)}</select>`)}${row('报考条件',`<select name="condition" required><option value="">请选择与本人对应的条件</option><option ${a.condition==='学历与专业工作年限条件'?'selected':''}>学历与专业工作年限条件</option><option ${a.condition==='取得初级资格后工作满3年'?'selected':''}>取得初级资格后工作满3年</option><option ${a.condition==='增报专业'?'selected':''}>增报专业</option></select>`)}${row('已取得初级注安资格',`<select name="junior">${opt('no','否',a.junior)}${opt('yes','是',a.junior)}</select>`,false)}${row('已取得中级注安资格',`<select name="middle">${opt('no','否',a.middle)}${opt('yes','是',a.middle)}</select>`,false)}</form><div class="tip-box ${req!==null&&Number(state.work.safetyYears)<req?'danger':''}"><strong>规则联动：</strong>${req===null?'请选择专业类别，系统将显示对应年限要求。':`${educationLabels[state.education.level]}、${majorLabels[a.majorType]}最低要求安全生产业务满${req}年；当前填报${state.work.safetyYears||0}年。`}</div></div>`;}
    if(state.applicationStep===3)body+=`<div class="substep active"><div class="tip-box"><strong>信息确认：</strong>以下内容由账号信息自动调用，请仔细核对。</div>${applicationSummary()}</div>`;
    if(state.applicationStep===4)body+=`<div class="substep active"><div class="commitment"><h3>专业技术人员资格考试报名证明事项告知承诺书（模拟）</h3><p>考试组织机构将依法依规告知报考人员证明事项名称、设定依据、证明内容和承诺方式。本模拟页面用于展示办理方式，不产生任何法律效力。</p><p>本人已知晓本次模拟填报不构成真实考试报名，并确认此前填写的信息用于模拟判断。正式报名时，本人将通过官方渠道如实填报信息，并承担不实承诺的相关责任。</p><p>选择不采用告知承诺制或不适用告知承诺制的人员，正式报名时应按照报考地考试组织机构要求接受人工核查并提交相关证明材料。</p></div><label class="commitment-check"><input type="checkbox" id="promiseCheck" ${a.promise?'checked':''}>我已阅读并选择采用告知承诺制方式（模拟）</label></div>`;
    body+=`<div class="button-row">${state.applicationStep>1?'<button class="secondary-btn" data-apply-prev>上一步</button>':''}<button class="primary-btn" ${state.applicationStep===4?'data-submit-application':'data-apply-next'}>${state.applicationStep===4?'提交模拟报名信息':'保存并继续'}</button></div>`;
    return panel('2026年度中级注册安全工程师职业资格考试',body,'考试报名');
  }
  function applicationSummary(){const a=state.application,p=state.personal,e=state.education,w=state.work;const items=[['姓名',p.name],['证件号码','110***********1234'],['报考地区',a.province||'—'],['报考级别',levelLabels[a.level]||'—'],['报考专业',a.profession||'—'],['报考科目',a.subjects.map(x=>subjectLabels[x]).join('、')||'—'],['学历层次',educationLabels[e.level]||'—'],['毕业院校',e.school||'—'],['所学专业',e.majorName||'—'],['工作单位',w.company||'—'],['工作年限',(w.workYears||0)+'年'],['专业年限',(w.safetyYears||0)+'年']];return `<div class="summary-table">${items.map(([k,v])=>`<div class="summary-item"><span>${k}</span><strong>${esc(v)}</strong></div>`).join('')}</div>`;}
  function review(){
    if(!state.applicationSubmitted)return panel('资格核查与缴费',`<div class="locked-box"><i>核</i><h2>尚未提交报名信息</h2><p>完成正式报名信息填写并提交后，可进入模拟资格核查与缴费流程。</p><button class="primary-btn" data-go="apply">进入考试报名</button></div>`,'考试报名');
    const steps=[['报名信息提交',true],['资格核查',state.reviewStatus==='passed'||state.paid],['网上缴费',state.paid],['报名完成',state.paid]];
    let action='';
    if(state.reviewStatus==='pending')action=`<div class="review-result"><div class="review-icon" style="background:#fff4dc;color:#c47a12">…</div><h2>资格核查中</h2><p>正式系统一般会在规定时间内完成在线或人工核查。本演示可直接模拟完成核查。</p><div class="button-row"><button class="secondary-btn" data-open-lead>申请人工复核指导</button><button class="primary-btn" data-pass-review>模拟核查通过</button></div></div>`;
    if(state.reviewStatus==='passed'&&!state.paid)action=`<div class="review-result"><div class="review-icon">✓</div><h2>资格核查通过</h2><p>请在规定时间内完成网上缴费。逾期未缴费通常视为放弃报名。</p><div class="payment-box"><span>模拟报名费用</span><br><strong>￥244.00</strong><p>本系统不会发起真实支付，也不会要求银行卡或验证码。</p><button class="success-btn" data-pay>完成模拟缴费</button></div></div>`;
    if(state.paid)action=`<div class="review-result"><div class="review-icon">✓</div><h2>模拟报名完成</h2><p>模拟缴费成功。建议保存报名表，并关注准考证打印时间。</p><div class="button-row"><button class="secondary-btn" data-open-lead>领取报名材料清单</button><button class="primary-btn" data-go="form">查看报名表</button></div></div>`;
    return panel('资格核查与缴费',`<div class="tip-box warning"><strong>演示说明：</strong>此处不连接考试机构审核系统，也不会产生真实费用。</div><div class="review-flow">${steps.map(([x,d],i)=>`<div class="review-step ${d?'done':i===1&&state.reviewStatus==='pending'?'current':''}"><i>${d?'✓':i+1}</i><strong>${x}</strong><span>${d?'已完成':'待办理'}</span></div>`).join('')}</div>${action}<div class="button-row"><button class="danger-btn" data-withdraw>撤回模拟报名</button></div>`,'考试报名');
  }
  function registrationForm(){if(!state.paid)return panel('报名表预览',`<div class="locked-box"><i>表</i><h2>报名表暂未生成</h2><p>完成模拟资格核查和缴费后，系统将生成报名表预览。</p><button class="primary-btn" data-go="review">查看办理进度</button></div>`,'考试报名');const a=state.application,p=state.personal,e=state.education,w=state.work;return panel('报名表预览',`<div class="tip-box"><strong>保存提示：</strong>部分地区考后资格审核可能需要报名表。正式报名完成后建议下载存档。</div><div class="application-paper"><div class="paper-head"><h2>中级注册安全工程师职业资格考试报名表</h2><p>2026年度 · 模拟样表</p></div><table class="paper-table"><tr><th>姓名</th><td>${esc(p.name)}</td><th>性别</th><td>${esc(p.gender)}</td></tr><tr><th>证件类型</th><td>居民身份证（模拟）</td><th>证件号码</th><td>110***********1234</td></tr><tr><th>报考地区</th><td>${esc(a.province)}</td><th>报考级别</th><td>${esc(levelLabels[a.level])}</td></tr><tr><th>报考专业</th><td colspan="3">${esc(a.profession)}</td></tr><tr><th>报考科目</th><td colspan="3">${esc(a.subjects.map(x=>subjectLabels[x]).join('、'))}</td></tr><tr><th>学历层次</th><td>${esc(educationLabels[e.level])}</td><th>所学专业</th><td>${esc(e.majorName)}</td></tr><tr><th>毕业院校</th><td colspan="3">${esc(e.school)}</td></tr><tr><th>工作单位</th><td colspan="3">${esc(w.company)}</td></tr><tr><th>工作年限</th><td>${esc(w.workYears)}年</td><th>专业年限</th><td>${esc(w.safetyYears)}年</td></tr><tr><th>办理方式</th><td colspan="3">采用告知承诺制（模拟）</td></tr></table><p class="paper-note">声明：本表由第三方模拟报名工具生成，不是正式考试报名表，不具备报名、审核、缴费或证明效力。</p><div class="paper-seal"><span>报名序号：MOCK-2026-00001</span><span>生成日期：${new Date().toLocaleDateString('zh-CN')}</span></div></div><div class="button-row"><button class="secondary-btn" onclick="window.print()">打印模拟报名表</button><button class="primary-btn" data-open-lead>领取正式报名材料清单</button></div>`,'考试报名');}
  function faqPage(){
    const catNames={account:['账','账号与注册'],photo:['照','报名照片'],education:['学','学历学位核验'],condition:['条','报考条件与年限'],subject:['科','专业与科目'],audit:['核','审核、缴费与报名表']};
    const groups=Object.entries(catNames).map(([cat,[icon,name]])=>`<section class="faq-group" data-faq-group="${cat}"><div class="faq-group-title"><i>${icon}</i><span>${name}</span></div>${faqData.filter(x=>x[0]===cat).map(([_,q,a])=>`<details class="faq-item" data-search="${esc(q+a)}"><summary>${esc(q)}</summary><div class="faq-answer"><p>${esc(a)}</p>${cat==='condition'||cat==='audit'?'<div class="answer-note">提示：各地区审核口径可能不同，请以报考地当年度考务通知为准。</div>':''}</div></details>`).join('')}</section>`).join('');
    return panel('报考常见问题',`<div class="help-hero"><h2>中级注册安全工程师报考问题库</h2><p>汇总新考生在注册、学历核验、工作年限、科目选择和资格审核中的高频疑问。</p></div><div class="faq-tools"><input class="faq-search" id="faqSearch" placeholder="输入问题关键词，如：学历、工作年限、照片、审核"><span class="faq-count" id="faqCount">共 ${faqData.length} 个问题</span></div><div class="faq-filters"><button class="active" data-faq-cat="all">全部</button>${Object.entries(catNames).map(([k,v])=>`<button data-faq-cat="${k}">${v[1]}</button>`).join('')}</div><div class="faq-groups">${groups}</div><div class="faq-empty" id="faqEmpty">没有找到相关问题，可以咨询报考顾问。</div>${offer('没有找到你的问题？','添加报考老师微信，获取一对一报名问题答疑','general')}`,'报考帮助');
  }
  function guidePage(){
    const nav=[['g1','注册账号'],['g2','照片上传'],['g3','完善信息'],['g4','正式报名'],['g5','办理方式'],['g6','审核缴费'],['g7','保存报名表'],['g8','专业选择']];
    return panel('新考生报名全流程攻略',`<div class="guide-layout"><aside class="guide-toc"><strong>攻略目录</strong>${nav.map(([id,n])=>`<a href="#${id}">${n}</a>`).join('')}</aside><article class="guide-article"><header class="guide-banner"><span>2026 PRE-APPLICATION GUIDE</span><h2>中级注册安全工程师<br>新考生报名全流程攻略</h2><p>从账号注册、照片处理到资格核查和报名表保存，一页看懂完整步骤。</p><div class="guide-meta"><span>适用人群：首次报考人员</span><span>阅读时间：约8分钟</span></div></header><div class="guide-disclaimer"><strong>重要说明：</strong>本攻略根据用户提供的2025报名流程资料重新整理，用于2026报名前预习。具体时间、材料和审核要求以报考地当年度官方通知为准。</div>
    <section class="guide-section" id="g1"><div class="guide-section-head"><span class="guide-number">01</span><div><h3>报名注册</h3><p>新考生第一步，老考生检查已有信息</p></div></div><div class="guide-section-body"><div class="guide-do-dont"><div class="guide-do"><strong>新考生</strong>提前注册账号，如实填写注册信息，牢记用户名、密码及绑定手机。</div><div class="guide-dont"><strong>老考生</strong>通常无需重复注册，但应补充完善信息并确认联系方式仍可使用。</div></div><h4>注册前建议准备</h4><ul class="guide-checklist"><li>本人常用手机号码与邮箱</li><li>有效身份证件，仅在官方报名平台填写</li><li>毕业证、学位证及学信网信息</li><li>工作单位和安全生产业务经历</li></ul><div class="guide-alert">不要将官方报名账号、密码、短信验证码交给他人代操作。</div></div></section>
    <section class="guide-section" id="g2"><div class="guide-section-head"><span class="guide-number">02</span><div><h3>准备并上传报名照片</h3><p>准备照片 - 审核工具处理 - 上传</p></div></div><div class="guide-section-body"><div class="guide-steps"><div class="guide-step"><b>1</b><strong>准备照片</strong><span>近期彩色标准1寸、白色背景、JPG/JPEG格式。</span></div><div class="guide-step"><b>2</b><strong>审核处理</strong><span>在电脑端使用正式报名平台指定的照片审核工具。</span></div><div class="guide-step"><b>3</b><strong>上传确认</strong><span>使用审核通过后保存的照片文件上传。</span></div></div><p>常见参考尺寸为25mm×35mm、295px×413px。正式要求以报名平台当年度提示为准。</p><div class="guide-alert">照片可能用于准考证、考场座次表和证书，上传成功后通常不便自行更换。</div></div></section>
    <section class="guide-section" id="g3"><div class="guide-section-head"><span class="guide-number">03</span><div><h3>完善账号信息</h3><p>信息完整度达到要求后才能进入考试报名</p></div></div><div class="guide-section-body"><div class="guide-steps"><div class="guide-step"><b>A</b><strong>个人信息</strong><span>姓名、证件、性别、民族、国籍地区、政治面貌。</span></div><div class="guide-step"><b>B</b><strong>学历学位</strong><span>毕业院校、证书编号、毕业时间、专业、层次、培养方式。</span></div><div class="guide-step"><b>C</b><strong>工作经历</strong><span>工作单位、单位性质、工作年月、专业职称和安全业务经历。</span></div></div><h4>学历在线核查</h4><p>系统通常会对境内高等教育学历学位信息进行在线核查。核查状态为未通过或需现场核查时，可按报考地要求准备学信网在线验证或认证报告，接受人工核查。</p><ul class="guide-checklist"><li>学历信息至少维护一条，选择符合报考条件的信息报名</li><li>无学位信息一般可以不填写学位</li><li>不要重复添加错误学历，应先核对证书和学信网信息</li><li>学历核查可能需要等待，不代表提交后立即出结果</li></ul>${offer('学历核验材料不会准备？','领取学信网验证报告申请指南 + 人工核查材料清单','education')}</div></section>
    <section class="guide-section" id="g4"><div class="guide-section-head"><span class="guide-number">04</span><div><h3>进入正式报名</h3><p>选择考试、地区，并完成四部分报名信息</p></div></div><div class="guide-section-body"><h4>选择考试与报考地区</h4><p>在报名入口开放后选择“中级注册安全工程师职业资格考试”和报考省市。原则上在工作地或居住地就近报名，部分城市可能设置单独入口。</p><h4>报名信息重点字段</h4><table class="guide-table"><thead><tr><th>字段</th><th>填写要点</th></tr></thead><tbody><tr><td>报考级别</td><td>考全科、免一科、免二科、增报专业。已通过部分科目的老考生仍按原级别报名。</td></tr><tr><td>报考专业</td><td>从七个专业实务类别中选择一个，应结合当前行业和职业发展方向。</td></tr><tr><td>报考科目</td><td>根据本年度计划勾选要参加的科目，注意成绩滚动周期。</td></tr><tr><td>报考条件</td><td>选择与本人学历、专业、资格和年限一致的条件条款。</td></tr><tr><td>资格证书</td><td>增报专业或通过初级资格路径报考的人员按实际情况填写。</td></tr></tbody></table><h4>确认三类信息</h4><ul class="guide-checklist"><li>个人信息：核对系统调用的姓名、证件、性别等</li><li>教育信息：选择用于本次报名的学历和学位</li><li>工作信息：区分工作年限与安全生产业务专业年限</li></ul>${offer('担心选错报考条件？','领取2026报考条件对照表 + 安全相关专业参考目录','conditions')}</div></section>
    <section class="guide-section" id="g5"><div class="guide-section-head"><span class="guide-number">05</span><div><h3>选择报名办理方式</h3><p>告知承诺制或非告知承诺制</p></div></div><div class="guide-section-body"><div class="guide-do-dont"><div class="guide-do"><strong>采用告知承诺制</strong>对本人符合条件、填报信息真实有效作出承诺。在线核查通过后，通常办理更便捷，但考试机构仍可抽查。</div><div class="guide-dont"><strong>不采用或不适用</strong>通常需要按要求接受人工核查，提交学历、工作年限、资格证书等证明材料。</div></div><div class="guide-alert">采用告知承诺制不等于不审核。任何在线核查未通过的项目，仍可能进入人工核查。</div></div></section>
    <section class="guide-section" id="g6"><div class="guide-section-head"><span class="guide-number">06</span><div><h3>等待资格核查并缴费</h3><p>审核通过不等于报名完成</p></div></div><div class="guide-section-body"><div class="guide-steps"><div class="guide-step"><b>1</b><strong>提交信息</strong><span>完成报名表并选择办理方式。</span></div><div class="guide-step"><b>2</b><strong>资格核查</strong><span>关注在线核查、材料上传或现场核查提示。</span></div><div class="guide-step"><b>3</b><strong>网上缴费</strong><span>审核通过后在规定时间内完成缴费。</span></div></div><p>缴费成功通常才视为报名完成。逾期未缴费一般按放弃报名处理，缴费后关键信息通常无法自行修改。</p></div></section>
    <section class="guide-section" id="g7"><div class="guide-section-head"><span class="guide-number">07</span><div><h3>保存报名表</h3><p>报名完成后的最后一项整理工作</p></div></div><div class="guide-section-body"><p>部分地区会实施考后资格审核，可能要求提供报名表、学历证明、工作年限证明等材料。完成正式报名后建议下载并保存报名表。</p><ul class="guide-checklist"><li>核对报名序号、姓名、地区、级别和专业</li><li>确认缴费状态显示成功</li><li>下载报名表并保存PDF或打印件</li><li>记录准考证打印时间和考试日期</li></ul></div></section>
    <section class="guide-section" id="g8"><div class="guide-section-head"><span class="guide-number">08</span><div><h3>七个专业怎么选</h3><p>优先考虑工作需要，其次考虑职业方向和备考基础</p></div></div><div class="guide-section-body"><table class="guide-table"><thead><tr><th>专业类别</th><th>适合行业/方向</th><th>学习重点</th></tr></thead><tbody><tr><td>煤矿安全</td><td>煤炭行业</td><td>通风、瓦斯、防灭火、粉尘、防治水和矿山救护</td></tr><tr><td>金属非金属矿山</td><td>金属非金属矿山行业</td><td>露天与地下开采、尾矿库、灾害防治</td></tr><tr><td>化工安全</td><td>化工、医药、危险化学品</td><td>工艺安全、特殊作业、危险品储存和应急救援</td></tr><tr><td>金属冶炼安全</td><td>冶金、有色冶炼</td><td>烧结、焦化、炼铁炼钢、煤气和有色金属加工</td></tr><tr><td>建筑施工安全</td><td>建设工程各行业</td><td>机械、临电、防护、脚手架、模板和专项工程</td></tr><tr><td>道路运输安全</td><td>客运、货运、危货、维修</td><td>运输安全、危货管理和应急处置</td></tr><tr><td>其他安全</td><td>上述行业以外的安全领域</td><td>危险物品、防火防爆、防触电及通用案例</td></tr></tbody></table><div class="guide-alert">专业选择不应只看所谓“难度排行”。在岗人员优先选择与工作行业匹配的类别；尚未确定方向的人员应结合长期职业规划判断。</div></div></section>
    <footer class="guide-footer-cta"><h3>已经看懂流程？现在走一遍模拟报名</h3><p>使用虚拟信息即可体验，不需要填写真实身份证、照片或工作单位。</p><div class="button-row"><button class="primary-btn" data-go="dashboard">进入模拟报名系统</button><button class="secondary-btn" data-open-lead data-offer="general">领取报名材料清单</button></div><p class="source-note">内容依据用户提供的《2025注册安全工程师考试报名全流程【新考生】》资料重新编写，并结合模拟系统流程组织；不复制原资料品牌及营销素材。</p></footer></article></div>`,'报考帮助');
  }
  function injectOffers(view){
    if(view==='education')root.querySelector('.panel-body')?.insertAdjacentHTML('beforeend',offer('学历核验不通过怎么办？','免费领取学信网验证报告申请指南 + 学历核验常见问题','education'));
    if(view==='work')root.querySelector('.panel-body')?.insertAdjacentHTML('beforeend',offer('工作年限不知道怎么计算？','免费领取安全生产业务年限计算表 + 工作证明模板','work'));
    if(view==='apply'&&state.applicationStep===2)root.querySelector('.substep.active')?.insertAdjacentHTML('beforeend',offer('你的条件到底能不能报？','免费领取2026报考条件对照表 + 安全相关专业参考目录','conditions'));
    if(view==='faq')root.querySelector('.help-hero')?.insertAdjacentHTML('beforeend','<div class="button-row" style="justify-content:flex-start;margin-top:14px"><button class="secondary-btn" data-go="guide">查看新考生报名全流程攻略</button></div>');
  }
  function filterFaq(){const query=(document.querySelector('#faqSearch')?.value||'').trim().toLowerCase();const active=document.querySelector('[data-faq-cat].active')?.dataset.faqCat||'all';let shown=0;document.querySelectorAll('[data-faq-group]').forEach(group=>{const cat=group.dataset.faqGroup;let groupShown=0;group.querySelectorAll('.faq-item').forEach(item=>{const matchCat=active==='all'||active===cat;const matchText=!query||(item.dataset.search||'').toLowerCase().includes(query);const visible=matchCat&&matchText;item.style.display=visible?'':'none';if(visible){shown++;groupShown++;}});group.style.display=groupShown?'':'none';});const count=document.querySelector('#faqCount');if(count)count.textContent=`显示 ${shown} / ${faqData.length} 个问题`;const empty=document.querySelector('#faqEmpty');if(empty)empty.style.display=shown?'none':'block';}
  function render(view=state.view){state.view=view;save();const renderers={dashboard,photo,personal,education,work,apply:application,review,form:registrationForm,faq:faqPage,guide:guidePage};root.innerHTML=renderers[view]();injectOffers(view);document.querySelector('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});}
  function formObject(id){const form=document.querySelector('#'+id);if(!form)return null;return Object.fromEntries(new FormData(form).entries());}
  function validateForm(id){const form=document.querySelector('#'+id);let ok=true;form.querySelectorAll('[required]').forEach(el=>{const invalid=!String(el.value).trim();el.style.borderColor=invalid?'#d83a3a':'';if(invalid)ok=false;});if(!ok)toast('请完成所有必填项目');return ok;}
  function fillDemo(){state.photoComplete=state.personalComplete=state.educationComplete=state.workComplete=true;state.photoName='模拟照片';state.personal={...state.personal,name:'张明（模拟）',birth:'1990-05-18',phone:'138****5678'};state.education={overseas:'no',certificate:'DEMO20260001',school:'华北示例大学',graduation:'2018-06',majorName:'安全工程',level:'bachelor',mode:'普通全日制',degree:'学士'};state.work={company:'示例安全技术有限公司',companyType:'民营企业',province:'北京',startWork:'2018-07',startSafety:'2019-01',title:'中级',titleDate:'2023-06-01',workYears:'8',safetyYears:'7'};state.application.province='北京';save();toast('演示资料已填充');render('dashboard');}
  function saveApplyStep(){const f=document.querySelector('#applyStepForm');if(!f)return true;if(!validateForm('applyStepForm'))return false;const data=formObject('applyStepForm');if(state.applicationStep===2)data.subjects=[...f.querySelectorAll('input[name="subjects"]:checked')].map(x=>x.value);state.application={...state.application,...data};save();return true;}
  function eligibility(){const a=state.application,e=state.education,w=state.work;if(a.level==='additional')return a.middle==='yes'?{ok:true,msg:''}:{ok:false,msg:'增报专业需已取得中级注册安全工程师职业资格。'};const need=rules[e.level]?.[a.majorType];if(need===undefined)return{ok:false,msg:'请选择明确的学历和专业类别。'};if(Number(w.safetyYears)<need)return{ok:false,msg:`当前条件最低要求安全生产业务满${need}年，您填报为${w.safetyYears||0}年。`};if(a.level==='exempt2'&&!['高级','正高级'].includes(w.title))return{ok:false,msg:'免二科需要高级或正高级工程师职称等条件，当前信息需要进一步核验。'};return{ok:true,msg:''};}

  document.addEventListener('click',e=>{
    const go=e.target.closest('[data-go]');if(go){e.preventDefault();render(go.dataset.go);return;}
    const nav=e.target.closest('[data-view]');if(nav){render(nav.dataset.view);return;}
    const close=e.target.closest('[data-close]');if(close){closeModal(close.dataset.close);return;}
    const faqCat=e.target.closest('[data-faq-cat]');if(faqCat){document.querySelectorAll('[data-faq-cat]').forEach(x=>x.classList.remove('active'));faqCat.classList.add('active');filterFaq();return;}
    if(e.target.closest('[data-open-lead]')){const trigger=e.target.closest('[data-open-lead]');const type=trigger.dataset.offer||'general';const offers={education:['学历核验通关资料包',['学信网验证报告申请指南','学历核验失败处理方法','人工核查材料清单','一对一学历问题答疑']],work:['工作年限证明资料包',['安全生产业务年限计算表','工作年限证明模板','单位盖章注意事项','一对一工作年限答疑']],conditions:['2026注安报考条件资料包',['2026报考条件对照表','安全相关专业参考目录','免一科/免二科条件说明','一对一条件预审']],general:['2026注安报名资料包',['2026报考条件对照表','报名材料准备清单','告知承诺制办理指南','一对一填报问题答疑']]};const [title,items]=offers[type]||offers.general;document.querySelector('#wechatTitle').textContent=title;document.querySelector('#wechatBenefits').innerHTML=items.map(x=>`<li>${x}</li>`).join('');openModal('leadModal');return;}
    if(e.target.closest('[data-demo-fill]')){fillDemo();return;}
    if(e.target.closest('[data-demo-photo]')){state.photoComplete=true;state.photoName='模拟照片';save();toast('已生成模拟证件照');render('photo');return;}
    if(e.target.closest('[data-save-personal]')){if(!validateForm('personalForm'))return;state.personal={...state.personal,...formObject('personalForm')};state.personalComplete=true;save();toast('个人信息已保存');render('personal');return;}
    if(e.target.closest('[data-save-education]')){if(!validateForm('educationForm'))return;state.education={...state.education,...formObject('educationForm')};state.educationComplete=true;save();toast('学历信息模拟核查通过');render('education');return;}
    if(e.target.closest('[data-save-work]')){if(!validateForm('workForm'))return;state.work={...state.work,...formObject('workForm')};state.workComplete=true;save();toast('工作经历已保存');render('work');return;}
    if(e.target.closest('[data-apply-next]')){if(!saveApplyStep())return;state.applicationStep=Math.min(4,state.applicationStep+1);save();render('apply');return;}
    if(e.target.closest('[data-apply-prev]')){saveApplyStep();state.applicationStep=Math.max(1,state.applicationStep-1);save();render('apply');return;}
    if(e.target.closest('[data-submit-application]')){state.application.promise=document.querySelector('#promiseCheck')?.checked||false;if(!state.application.promise){toast('请阅读并勾选模拟告知承诺');return;}const result=eligibility();if(!result.ok){toast(result.msg);openModal('leadModal');return;}state.applicationSubmitted=true;state.reviewStatus='pending';save();toast('模拟报名信息已提交');render('review');return;}
    if(e.target.closest('[data-pass-review]')){state.reviewStatus='passed';save();toast('模拟资格核查已通过');render('review');return;}
    if(e.target.closest('[data-pay]')){state.paid=true;save();toast('模拟缴费成功');render('review');return;}
    if(e.target.closest('[data-withdraw]')){state.applicationSubmitted=false;state.reviewStatus='none';state.paid=false;state.applicationStep=1;save();toast('已撤回模拟报名');render('apply');return;}
  });
  document.querySelector('#openNotice').addEventListener('click',()=>openModal('noticeModal'));
  document.querySelector('#mobileMenu').addEventListener('click',()=>document.querySelector('#sidebar').classList.toggle('open'));
  document.querySelector('#clearData').addEventListener('click',()=>{if(confirm('确认退出账号并清空全部模拟填报数据吗？')){localStorage.removeItem(STORE);localStorage.removeItem(USER_STORE);platformUser=null;state=structuredClone(defaultState);render('dashboard');document.querySelector('#registerGate').classList.add('open');document.querySelector('#registerGate').setAttribute('aria-hidden','false');toast('已退出模拟平台');}});
  root.addEventListener('change',e=>{if(e.target.id==='photoFile'&&e.target.files[0]){const file=e.target.files[0];if(!file.type.startsWith('image/')){toast('请选择图片文件');return;}const reader=new FileReader();reader.onload=()=>{document.querySelector('#photoPreview').innerHTML=`<img src="${reader.result}" alt="本地预览照片">`;state.photoComplete=true;state.photoName=file.name;save();toast('图片仅在当前页面本地预览');};reader.readAsDataURL(file);}});
  root.addEventListener('input',e=>{if(e.target.id==='faqSearch')filterFaq();});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(x=>closeModal(x.id));});
  document.querySelector('#sendCode').addEventListener('click',()=>{const phone=document.querySelector('#registerForm').elements.phone;if(!/^1[3-9]\d{9}$/.test(phone.value)){phone.closest('label').querySelector('small').textContent='请先输入正确的手机号码';return;}document.querySelector('#registerForm').elements.code.value='6666';toast('体验验证码已自动填入');});
  document.querySelector('#registerForm').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;let ok=true;form.querySelectorAll('input[required]').forEach(el=>{let msg='';if(!el.value.trim())msg='请完成此项';if(el.name==='phone'&&el.value&&!/^1[3-9]\d{9}$/.test(el.value))msg='请输入正确的11位手机号码';if(el.name==='code'&&el.value!=='6666')msg='体验验证码为6666';el.closest('label').querySelector('small').textContent=msg;if(msg)ok=false;});if(!form.elements.privacy.checked||!form.elements.disclaimer.checked){document.querySelector('#registerError').textContent='请阅读并同意协议、隐私政策和模拟系统免责声明';ok=false;}else document.querySelector('#registerError').textContent='';if(!ok)return;platformUser={name:form.elements.name.value.trim(),phone:form.elements.phone.value,createdAt:new Date().toISOString()};localStorage.setItem(USER_STORE,JSON.stringify(platformUser));state.personal.name=platformUser.name;save();document.querySelector('#registerGate').classList.remove('open');document.querySelector('#registerGate').setAttribute('aria-hidden','true');render('dashboard');openModal('noticeModal');});
  render(state.view);
  if(!platformUser){document.querySelector('#registerGate').classList.add('open');document.querySelector('#registerGate').setAttribute('aria-hidden','false');}
})();
